### ISSUE TITLE
Allow users to set a maximum or fixed prefix width

### ISSUE THREAD

**Issue by BlacklightShining** [ubergeek42/weechat-android#168]
Since the 0.9 update, the _maximum width of prefix_ option sets a fixed width for the prefix. Please add an option to make this a _maximum_ instead, returning to the previous behavior of keeping the prefix width for each buffer at the minimum necessary to display the longest nick, or the maximum width specified, whichever is less.

**Comment by jiggie42** [comment]
I don't know how difficult this would be to add, but I would find it useful.  I think in the meantime, if we could rename the Settings option that would be appreciated. *begins work on pull request*

**Comment by jiggie42** [comment]
I misunderstood how this setting interacts with the overall alignment.  My understanding is that the issue here can be resolved by adjusting the "Look & feel" Settings text contained at app/src/main/res/values/strings.xml and other translations.  It was determined the current behavior is "max" when it's "left-aligned" and "fixed" when it's "right-aligned"
thanks @oakkitten

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
