### ISSUE TITLE
Allow customising colour scheme for IRC view

### ISSUE THREAD

**Issue by abjugard** [ubergeek42/weechat-android#219]
Many of the colours I have for nicks and their messages are too dark with the black background in WeeChat-Android. On Linux I have a colour scheme with a slightly lighter background and slightly more pale colours, making the colours easier to distinguish there. 

Allowing users to customise the colour scheme, while obviously a pretty difficult task, would go a long way towards improving the readability of some WeeChat configurations.

**Comment by ubergeek42** [comment]
Are you running the latest version? There was a fix a short time ago(may 22) that changed the colors of blue and green to make them a bit easier to read: https://github.com/ubergeek42/weechat-android/pull/180

It sounds like you mean changing just the standard 16 base colors? I think that's something we could consider(and would make it easier to add "themes").

Alternatively, if you change all of your color values to use numbers(greater than 16 I think) instead of names in your weechat color config/theme, it'll _probably_ be reflected properly in the app. At least for things where we're getting the color information from weechat itself(All chat lines basically). I think highlight color is on our end though.

The standard 256 colors can be found here: http://www.calmar.ws/vim/256-xterm-24bit-rgb-color-chart.html

Looks like I actually need to change some of the color codes I'm using anyway, the basic 16 don't match what they should be anyway(looks like I took weechat's color names and used the html color codes for each one). I also think the base 16 colors of the "extended color set" I am using isn't quite right either.

**Comment by abjugard** [comment]
I think most users of WeeChat-Android will be familiar with terminal colour schemes, and as such the best solution might be to implement terminal-like colour scheme customisation. It would certainly make me happy!

For the record, colours 12 and 13 are the ones I'm having the biggest issues with, they look fine with my urxvt colour scheme, but are way too dark on my phone.

Phone:
![screenshot_2015-07-19-01-27-06](https://cloud.githubusercontent.com/assets/287697/8763949/adcfcaba-2db6-11e5-9f3b-8df7e0dcd4e6.png)

Terminal:
![screen shot 2015-07-19 at 01 17 45](https://cloud.githubusercontent.com/assets/287697/8763908/c5227dea-2db4-11e5-9252-b55b0c21b32d.png)

**Comment by abjugard** [comment]
This one is especially beautiful as well, as long as we're discussing colours hehe.
![screenshot_2015-07-19-02-03-27](https://cloud.githubusercontent.com/assets/287697/8764036/639c2f1e-2dbc-11e5-87a2-8d1a997ba455.png)

Basically my nick gets assigned a colour which is pretty much impossible to distinguish from the highlight colour, gets pretty confusing when someone else has the same colour and gets mentioned along with me in a highlight.

**Comment by ubergeek42** [comment]
Fixed in the most recent version. I'll try to write up some docs on how to use it in a little bit

**Comment by ubergeek42** [comment]
https://github.com/ubergeek42/weechat-android/wiki/Custom-Color-Schemes

Feel free to edit the guide if it isn't clear, or ping me directly for questions regarding them.

**Comment by abjugard** [comment]
This is wonderful news, thank you!
