### ISSUE TITLE
[feature request] Local relay host

### ISSUE THREAD

**Issue by sentriz** [ubergeek42/weechat-android#238]
A nice feature that could be added, if anyone is up for it would be a local relay host.

The setting *Relay host* would still be present, but *Local relay host* and *Local relay host SSID* would be added.
This would work as you would imagine - if you're not connected to the Wi-Fi network in *Local relay host SSID*, then use *Relay host* as normal, otherwise, use *Local relay host* to connect to weechat. Also, a checkbox to disable local settings might be good for people who only use weechat-android on their local network, where they should just use *Relay host* as normal.  

I would find this very useful because I wouldn't have to keep changing the *Relay host* in weechat-android when I have no Internet at home, which is quite frequently.

Example config:

Relay host | Local relay host SSID | Local relay host
:-- | :-- | :--
vps.my_website.com | HOME_WIFI | 192.168.1.15

Thanks! Just a suggestion,
Senan

**Comment by oakkitten** [comment]
what you want to do is make use of “nat hairpinning” on your router. i just tested it on my 7 years old $13 router and it works fine without internet connection. on my router it's not a feature that can be disabled (it's never even mentioned anywhere), but it's often disabled on other routers by default. now, unless you are running your own dns server, you obviously won't be able to use your host in such setup, but as long as your router knows its ip address (have to have static wan ip) and wa knows your router's ip, and if you disable data to make sure your device sticks to “internet-less” wifi instead of cellular, you will be able to connect.

hairpinning is more or less universally available. alternatively, you probably can: make use of ipv6 (no need for nat), dns views (different ip resolved inside and outside the network), some kind of dns hijacking/iptables rule (most android phones have iptables). probably there are apps that do some fiddling with dns, too.

i'm closing this issue as it only seems to be relevant in two cases: when your networking equipment uses vacuum tubes, or when you have a weird dynamic ip setup and frequent network outages. as wa is of little use offline, the second case seems not very valid. either way, individual applications are *not supposed* to deal with this.
