### ISSUE TITLE
Readd quit button

### ISSUE THREAD

**Issue by maxfragg** [ubergeek42/weechat-android#252]
is there any intention behind removing the quit-button?

**Comment by oakkitten** [comment]
the service is now stopped when you manually disconnect, so when you do that and press the back button (or swipe the application from the recent application list) you are effectively doing what quit button did. (quit button was a real quit button in some early version of the application but since killing processes is a bad bad thing on android it was changy changed a long time ago and was essentially a fake<sup>ha ha we tricked you users<sup>aw yis</sup></sup>)
