### ISSUE TITLE
f-droid update

### ISSUE THREAD

**Issue by ghost** [ubergeek42/weechat-android#282]
the current version in f-droid is 0.10 ... how can we get an update for 0.12?

**Comment by Mikaela** [comment]
I think you contact F-Droid as I have understood the apps in it aren't mostly affiliated with F-Droid.

**Comment by krt16s** [comment]
We failed to detect updates because `versionCode gitVersionCode()` is now used. We dont evaluate any gradle stuff (variables, methods, ...) but use a simple scraper to extract information. I manually updated to 0.11 and it should be done tomorrow.

On 0.12: I don't see a tag for it, is it released?

**Comment by ardumont** [comment]
Hello,

just so you know, it'd be good to update to the superior version 0.12 (google play, f-droid).

I failed to setup weechat-android with 0.11 (on oneplus):
- because i did not know it was mandatory to set a password on a weechat relay (since it's an option in main weechat, it should not be mandatory here). 
- And weechat-android-0.11 do not show any error in this regard... It just waits there... and of course do not connect (apparently doing nothing...)

So after seeking out some issues here, i got some hints...
Notably, I tried `adb logcat` but got submerged by logs that i tried to filter but, after some time, i did not have the patience any longer to do so... It's late here and i need some sleep ^^

Reading again the docs, i saw the 0.12 changelog entry and got the idea to try that one.
Updating to 0.12-dev made this error apparent since weechat-android told me this time.
(still, it's not really obvious for a user that you need to install manually some dev version) 

After that, coming back to 0.11, fixing the empty relay pass setup thingy.
And the error disappeared ^^ yeah...
Or so i thought, I had a new error about permission on my private key (well, still progress ^^)

I'm no android power-user (and my phone is not rooted, could be irrelevant, don't know) so i did not know which user/group should have been set to the key (keys generated either from GNU/Linux and copied via `adb push` or generated by connectBot and copied content on some accessible path.... same result with permission errors).

Finally, i just stick with 0.12-dev since the UI got updated for the best ^^
(private key import from phone's storage, known host file import, awesome by the way).

Anyway, thx for weechat-android.

An happy user now that it works ^^

Cheers,

**Comment by aeonsablaze** [comment]
Still no sign of 0.12 on f-droid or google play.

**Comment by krt16s** [comment]
I just added 0.12-git to the build qeueu. It should show up tomorrow on fdroid. However, this is a manual update, fdroid will not propose it (unless unstable updates is checked).

Note that development of this app pretty much seems stalled.

**Comment by ainola** [comment]
This can be closed as 0.12-git is in the repositories
