### ISSUE TITLE
Remove unused maven repo

### ISSUE THREAD

**Issue by krt16s** [ubergeek42/weechat-android#286]
It seems like there is a unused maven repo setup at https://github.com/ubergeek42/weechat-android/blob/master/build.gradle#L4 -- could you remove this or point me to what dependencies are fetched from it? I just might have the dep in my mavenlocal or gradle cache, so I didnt experience any issues when disabling that repo...

**Comment by ubergeek42** [comment]
The comment above says "viewpagerindicator", looking at the history of the android app build file[1] shows it was (probably) for actionbarsherlock's viewpagerindicator. Since we don't use that anymore it seems safe to remove.

[1] https://github.com/ubergeek42/weechat-android/blob/master/weechat-android/build.gradle
