### ISSUE TITLE
send-button on paste

### ISSUE THREAD

**Issue by unhammer** [ubergeek42/weechat-android#335]
When I paste e.g. an URL into the chat window without my keyboard showing, I have to first click in the field to make the keyboard show up, and then click "send". This feels slow. Could we either have the keyboard show on paste, or just a send button if there's something in the field but no keyboard?

**Comment by ubergeek42** [comment]
There's a toggle in settings to show a send button all the time, does that
solve the problem? Or do you want it hidden and to only show when the field
is non empty and the keyboard isn't showing?

On Feb 10, 2017 06:19, "Kevin Brubeck Unhammer" <notifications@github.com>
wrote:

When I paste e.g. an URL into the chat window without my keyboard showing,
I have to first click in the field to make the keyboard show up, and then
click "send". This feels slow. Could we either have the keyboard show on
paste, or just a send button if there's something in the field but no
keyboard?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ubergeek42/weechat-android/issues/335>, or mute the
thread

**Comment by unhammer** [comment]
> There's a toggle in settings to show a send button all the time, does that
> solve the problem? Or do you want it hidden and to only show when the field
> is non empty and the keyboard isn't showing?

Yeah, I like having the TAB button showing when typing, and having send
as well makes the text field really tiny …

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
