### ISSUE TITLE
No Buffer after connection

### ISSUE THREAD

**Issue by Chell256** [ubergeek42/weechat-android#342]
I can see on my server that my client has connected to the server 
`relay: new client on port 9001: 1/weechat/1.2.3.4`
but the app is stuck in the connecting screen.

**Comment by ubergeek42** [comment]
Upgrade to the nightly build, should be fixed there.

If you're already on the nightly build, can you give some more
details(Android version, app version, Weechat version)


On Mar 5, 2017 17:01, "Eisbaer" <notifications@github.com> wrote:

I can see on my server that my client has connected to the server
relay: new client on port 9001: 1/weechat/1.2.3.4
but the app is stuck in the connecting screen.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ubergeek42/weechat-android/issues/342>, or mute the
thread

**Comment by Chell256** [comment]
That fixes ist, thanks
