### ISSUE TITLE
Changed notifications on nightly force the notification to stay in the notification bar

### ISSUE THREAD

**Issue by witheld9** [ubergeek42/weechat-android#379]
On the stable release on Oreo, the connection notification is hidden and does not appear on the notification bar; but on nightly the icon is always visible. I believe it is because of the addition of a disconnect button.

**Comment by mhoran** [comment]
This is a function of Oreo's notification channels. It's no longer possible for the developer to hide the notification icon. However, the user can set the"priority" of the notification to low by sliding the notification to the left and clicking the cog. Then click "all categories", "Connection Status", "Importance" and set to low.

It may be that this behavior worked as you describe in 8.0, but in 8.1, notification channels are required on order for the notification to be hidden at all. That also means that 8.0 is affected, since notification channels were released in Oreo.

On December 23, 2017 9:17:14 AM EST, witheld9 <notifications@github.com> wrote:
>On the stable release on Oreo, the connection notification is hidden
>and does not appear on the notification bar; but on nightly the icon is
>always visible. I believe it is because of the addition of a disconnect
>button.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ubergeek42/weechat-android/issues/379

-- 
Sent from my mobile device.

**Comment by witheld9** [comment]
No stable still acts like the priority is low by default on 8.1. I'm digging around and would setting your channel's "importance level" to IMPORTANCE_LOW not designate it as a "by the way" notification?

**Comment by witheld9** [comment]
Sorry "IMPORTANCE_LOW" would be wrong,https://developer.android.com/guide/topics/ui/notifiers/notifications.html#Priority , it seems like 
https://developer.android.com/reference/android/app/NotificationManager.html#IMPORTANCE_NONE would be the importance to set as channels with that importance will not show in the shade

**Comment by witheld9** [comment]
This is also why notifications are making a noise when set to none, the priority is wrong

**Comment by mhoran** [comment]
Yes, that is because any importance lower than `IMPORTANCE_LOW` specified by the developer is bumped to `IMPORTANCE_LOW` by Android. See the bug I reported in 8.1 developer preview: https://issuetracker.google.com/issues/69987046. Note that `IMPORTANCE_LOW` does not translate to the same low importance in the notification UI. `IMPORTANCE_MIN` corresponds to low in the UI.

This is not documented anywhere, as I noted in my bug report. The user (you) must change the notification priority to make the icon disappear for foreground service notifications.
