### ISSUE TITLE
Tab-completing a nickname at the beginning of a message should activate a single capital

### ISSUE THREAD

**Issue by Porkepix** [ubergeek42/weechat-android#385]
When user tab-complete a nickname as first word of a message (with colons added at the end), first character after the space should be capitalized as it's most of the time to write a sentence.
This could also be an option the user can configure, preferably defaulting to capitalizing the first letter.

**Comment by Zopieux** [comment]
I beg to differ: this is a matter of taste. As far as I can tell, on the IRC channels I'm in, a large majority of people don't capitalize their messages. We could argue that capitalizing would be more consistant with the no-nickname messages, but to me the real issue is the keyboard capitalizing messages altogether. I'm not even sure Android apps have control over this, it may be an parameter of the keyboard provider itself.

**Comment by Porkepix** [comment]
Well, this is the way it's done on mobile for now a very long time. Those keyboards are far less usable than a real keyboard, so this kind of assisting tricks is more than welcome (when it does what you want. Otherwise, yeah, that's annoying).
Here, as someone who tries to write with a correct language, a sentence start with a capitalized letter and this is the kind of little things I find helpful. My opinion though. Maybe I'm the only one thinking this ? :p

**Comment by oakkitten** [comment]
i hate people who write stuff like “Bob: Hello!” even more than people who put two spaces after a period.

**Comment by mhoran** [comment]
In general, I don't capitalize the sentence that begins after a nick. I do generally capitalize sentences that don't start with a nick, but to me the nick itself is the start of the sentence and has the appropriate capitalization based on the nick itself.

This could certainly be achieved via an option, but I think we already have enough options and adding yet another just clutters the UI. I hope you find it reasonable to just capitalize the next letter itself.

Thanks for opening an issue, though!
