### ISSUE TITLE
Scroll position is lost on screen rotation

### ISSUE THREAD

**Issue by Porkepix** [ubergeek42/weechat-android#388]
If user rotate the screen while scrolled in the backlog of a chan, then scroll position is lost instead of being saved and repositioned at the same place, this shouldn't be the case (especially user can accidentally rotate the screen).

**Comment by oakkitten** [comment]
this is the result of us not saving scroll position at all. if you swipe the buffer away (1 or more screens left or right), it will get eventually recreated and the position will be reset to bottom. this is (or was) a bit intentional. it's easy enough to not notice that you are not at the bottom, so it'd be easy to miss new messages if the position is not reset once in a while. so jumping to bottom once in a while kind of helped here?

so a fix to this should include a floating “go to bottom” button

**Comment by Porkepix** [comment]
Thing is, while the swipe between buffers explanation makes sense, and this case might not have scroll position saved (especially, it would mean keeps all fetched lines in memory, while it currently forget about them), the case I describe is especially painful: if screen rotation isn't locked, it's kinda easy when you move (walk, metro and so on) to have phone accidentally rotate the screen. And in such situations, it's very very frustrating, especially when you came back a lot in your backlog, to have to scroll for years to try to find back where you was in the buffer.

**Comment by oakkitten** [comment]
yeah and i agree, i just wanted to note that a solution to this would have to require a new UI element which are a bit of a pita to get right. (and i personally dislike those go to bottom buttons.) alternatively, perhaps we could make sure that the message on the bottom of the screen is cut in half or something.

the history part of #389 is another issue and i kept it separate as this isn't an UI issue per se and would have to be fixed differently. currently we are recreating the whole buffer list from the grounds up. looking at the lines we had before would be therefore a bit hard to implement but the idea itself isn't unreasonable so

**Comment by oakkitten** [comment]
this has been fixed 870dc3c57141e49ff721cf5a98ed5d3b8ece0ad8
