### ISSUE TITLE
History and scroll position is lost on reconnect

### ISSUE THREAD

**Issue by Porkepix** [ubergeek42/weechat-android#389]
Considering a user that can move with its phone in bad network conditions (eg. undergroud) or simply switching between carrier and wifi network, it's gonna cause WeeChat to disconnect and then reconnect/resync.

There's no issue on disconnect. However, when Weechat-Android is going to reconnect, all the "more history" backlog will disappear and need to be fetched again (which might be impossible under bad network conditions), and it'll also result in loosing the scroll position even when application is on foreground with user reading the channel.

**Comment by oakkitten** [comment]
there's a slight problem with keeping lines between reconnects that i'm not sure how to best solved. imagine this scenario:

1. w-a connectes to WeeChat
2. line "a" appears in a buffer, which w-a receives
3. w-a disconnects
4. line "b" appears in a buffer, which w-a doesn't receive
5. w-a reconnects
6. line "c" appears in a buffer, which w-a receives

now WeeChat contains lines "a", "b", and "c". but w-a is only aware of "a" and "c". this is a problem because until w-a requests and receives all lines from WeeChat, these lines are what it can display. due to network issues etc it may never receive this lines.

i think this inconsistency can be solved in a number of ways:

1. discard old lines and only show "c". this will suck if you open the buffer right away after reconnecting
2. discard new lines and only show "a". this will suck if you open the buffer  a long time after reconnecting
3. request lines for all synchronized buffers upon reconnection. depending on the number of buffers & synchronization mode, this can be a very expensive operation
4. show a separator between "a" and "c". 

the last option can be achieved by requesting the last line pointer for each buffer (cheap) and comparing it with the pointer of the last line we've got. if not a match, we know that a buffer received a new line. we show a separator between "a" and "c", and upon focusing the buffer the lines are synced and the separator is animated into the missing lines

a problem with this is that many buffers receive invisible lines much more often than visible lines. so the real-life "a", "b" and "c" can be in fact:

> bob: hello!
> <-- margaret leaves
> alice: hey bob!

which would be displayed as the following, where 〰 is the separator:

> bob: hello!
> 〰
> alice: hey bob!

and upon line syncronization, if line filtering enabled, as this:

> bob: hello!
> alice: hey bob!

here's a [video demostration of the problem](https://i.imgur.com/H36Ev15.mp4) (slomo)

i think this doesn't look very good. so far (barring super rare examples) lines can only change to expand (e.g. media fetched, lines replace the separator 〰, lines get unhidden by smart filter). but in this case the separator is collapsing. it looks weird.

an obvious solution would be to determine if the last *visible* line of the buffer has changed. but i'm not sure if there's a way to request the pointer of the last *visible* line of the buffer. perhaps @flashcode could tell if there is a way :s

***

if you want to test, solution 4, with the problem above, has been implemented as a part of the search branch. i personally like it but maybe "request lines for all synchronized buffers upon connect" can be a setting. comments welcome

**Comment by oakkitten** [comment]
...the problem above can be somewhat mitigated by requesting more than one line pointer, say, 25 per buffer

**Comment by oakkitten** [comment]
these changes have been merged into master 870dc3c57141e49ff721cf5a98ed5d3b8ece0ad8
