### ISSUE TITLE
TOTP for weechat-android

### ISSUE THREAD

**Issue by shibumi** [ubergeek42/weechat-android#415]
We all know, that the `weechat protocol` is basically remote-code-execution on your server. So you all should have a good `weechat relay` password. This has changed with weechat version `2.4`. Weechat `2.4` comes with `TOTP` support for the weechat relay: https://weechat.org/files/changelog/ChangeLog-devel.html

```
relay: add support of Time-based One-Time Password (TOTP) as second authentication factor in weechat protocol
```

I suggest implementing `TOTP` in the `weechat android client` as well. This way we would have at least `TOTP` and a password for the relay, instead of just a password. This would be a huge security increase.

More can be found here: https://weechat.org/blog/post/2019/01/14/Support-of-TOTP

**Comment by mhoran** [comment]
While I see the value of adding additional security to the relay protocol (and generally support TOTP), this seems like a really poor user experience for mobile devices. Every time the client reconnects, it will have to ask for a challenge -- which, at least where I live, happens quite often.

I would rather see increased usage of the SSH connection type, which can enforce the requirement of public key authentication. Also, the SSL method could be extended to support mutual TLS, instead of just password. For the case of WebSocket connections, using both a secure password and a random path should provide sufficient security. Theoretically the relay client could support mutual TLS for WebSocket connections as well.

While I don't think we'd turn away a PR that adds this functionality, I can't justify implementing it myself in the specific case of mobile usage.

**Comment by shibumi** [comment]
I absolutly agree with you that TOTP is quite unhandy on mobile devices, but it would improve security a lot. SSH connection is an alternative, but with SSH connection comes basically code execution (which we have already with the weechat protocol itself). TOTP would be just optional. I don't have much experience with android java applications, but I guess it would be just an optional text box in the settings menu + an additional value in the weechat `init string`. I can maybe have a look on this.

Another Solution would be a small TOTP safe inside of the weechat android app. This way you could retrieve the TOTP token automatically on every reconnect and you would need the TOTP key just once for the installation on your client. (But this would destroy the whole philosophy of 2 factor authentication, I guess).

**Comment by oakkitten** [comment]
as i understand this, totp is useful in 2 cases

* when we have a passive mitm that can eavesdrop but not send weechat commands (you can probably get the secret through a command)

* when your OS is somehow unencrypted/unlocked so that someone who can get access to your phone can get your passwords stored in the apps

the former we can likely ignore, but for the latter you could use a password prompt (not really user-friendly) or some kind of an intent that gets the otp from a third-party app, which isn't really that much different to getting the password itself... but still useful, i guess. google authenticator or sth?

**Comment by mhoran** [comment]
Let's trust the system and TLS/SSL/etc to keep the connection itself secure, and reduce this to the problem of ensuring that only authorized users can connect to the relay. If you know that my relay is on example.com port 1423, then you can either get the password somehow, or guess it, and then get exec access on my host.

TOTP (and Google Authenticator, YubiKey, etc.) adds a second factor that makes it impossible to connect with _just_ the password. So then you have to enter the challenge as well as the password, every time you connect.

I think this is a pretty poor UX and would myself encourage leveraging alternative methods of increasing security, but I'm fine with someone else implementing this feature.

**Comment by twizmwazin** [comment]
I know this issue is somewhat stale now, but I think @shibumi made a really good point: in-app key store. This would allow the user to enter the TOTP key once in the app, and then the app will be able to use this to generate login tokens. It would still provide most of the security benefits, namely that password alone is not sufficient, but it would maintain the current UX. This somewhat violates the notion of "something you have, something you know" with 2fa, but in reality most users are storing their TOTP keys on their phones anyways.

**Comment by oakkitten** [comment]
as i understand it, every benefit that totp with the key stored in app might have is surpassed by the new `handshake` command (#444). the benefits of google authenticator et al are defeated by poor ux. i'll be closing this, then~
