### ISSUE TITLE
wrong error message for expired certificate

### ISSUE THREAD

**Issue by flokli** [ubergeek42/weechat-android#416]
Did set up a connection to Weechat through SSL.

The ssl certificate expired, but very confusingy, the error message keeps telling an invalid hostname is the reason:

```
Invalid hostname

You are trying to connect to xxxxx but the certificate is only valid for the following hosts:

(none)
````

**Comment by flokli** [comment]
Tested on v0.13-13-g4645c45.

**Comment by oakkitten** [comment]
current version is showing this for `expired.badssl.com`:

<img src="https://user-images.githubusercontent.com/1710718/89459629-db0b3b00-d760-11ea-89b1-b1fdb9917c82.png" width=300>

is the issue still relevant for you?

**Comment by flokli** [comment]
I assume it's fixed then. Closing.

**Comment by oakkitten** [comment]
i'm not sure we should be accepting expired certificates at all. 

it seems that currently the stuff on the screenshot is all the app is showing. i'm not sure what happens if the certificate was untrusted and not expired, we accept it, and *then* it expires. i think maybe we don't produce any warning in this case at all.

thus if we go the path of accepting expired certificates we will probably need to have a mechanism of separating expired and non-expired untrusted certificates... might require more work to do that? probably we simply shouldn't trust any expired certificates period.

i'm reopening this until this is resolved then

**Comment by nomis** [comment]
Expired certificates should not be accepted; make the certificate expire in 100 years if you want to workaround this.

It's also going to mask the fact that a cert was verifiable to a public CA in the past, allowing those to be reused after expiry too.
