### ISSUE TITLE
Please add support for ed25519.

### ISSUE THREAD

**Issue by BlackDex** [ubergeek42/weechat-android#438]
Hello there,

The library used for ssh is rather old compared to all the security changes.
SHA1 for example has been broken and the client can only use those as its strongest attempts to connect.

There is a newer ssh library available for java/android: https://github.com/hierynomus/sshj
Maybe that could help give the support of these newer protocols to the weechat android client.

**Comment by BlackDex** [comment]
JuiceSSH just presented an update today that they swichted over to libssh to support this.

**Comment by oakkitten** [comment]
i also tried using [sshlib](https://github.com/connectbot/sshlib) (*not* libssh)

pros:
  * all those of sshj
  * might be even faster than jsch

cons:
  * library code requires a bit of tweaking to work atm

with some tweaking i was able to put EC/RSA keys into the secure `AndroidKeyStore`. using the stored key is pretty simple:

```java
KeyStore ks = KeyStore.getInstance("AndroidKeyStore");
ks.load(null);
PrivateKey privateKey = (PrivateKey) ks.getKey("zoo", null);
PublicKey publicKey = ks.getCertificate("zoo").getPublicKey();
KeyPair keyPair = KeyPair(publicKey, privateKey);
```

this gets us a `KeyPair` that can be used to authenticate the connection:

```java
connection.authenticateWithPublicKey(sshUsername, keyPair);
```

this doesn't work out of the box as the library is casting private keys to `RSAPrivateKey` etc: `android.security.keystore.AndroidKeyStoreRSAPrivateKey cannot be cast to java.security.interfaces.RSAPrivateKeybut`. this is not necessary and can be [mended](https://github.com/oakkitten/sshlib/commit/de4f543759016043944122934cda4e08824cedef)

while this is good, the problem is putting these keys into the key store. you can get a `KeyPair` from the raw data:

```java
char[] charKey = new String(sshKey, StandardCharsets.ISO_8859_1).toCharArray();
KeyPair keyPair = PEMDecoder.decode(charKey, passphrase);
```

and then you would put it into the key store:

```java
KeyStore androidKeystore = KeyStore.getInstance("AndroidKeyStore");
androidKeystore.load(null);
androidKeystore.setKeyEntry("zoo", keyPair.getPrivate(), null, new Certificate[]{
        generateCertificate(keyPair)
});
```

the problem is that we don't easily have `generateCertificate()`. this certificate is useless for us as all we do is call `getPublicKey()` on it. but it still must be accepted by the key store. so we can either fake it (but how?) or generate a self-signed certificate. the latter is doable but it requires `BouncyCastle`. [this code](https://stackoverflow.com/a/59182063/1449683) worked for me. there are some alternatives such as using `sun.security.x509` but this package is apparently not inside android and i'm not sure it can be easily imported.

so, should we include bouncy castle for the sake of storing RSA/EC ssh keys? or maybe this whole idea is nuts?

p.s. perhaps it's also possible to somehow use [`WrappedKeyEntry`](https://developer.android.com/reference/android/security/keystore/WrappedKeyEntry.html) but this sounds even more complicated

**Comment by oakkitten** [comment]
so i think this is very good actually. code [here](https://github.com/ubergeek42/weechat-android/commits/sshlib-aks) builds [here](http://weechat-android.ubergeek42.com/index-sshlib-aks.html)

pros:

* Ed25519!
* keys are now stored in security hardware when possible. so far it's RSA and ECDSA and also DSA up to api 23—all confirmed in my testing
* you'll have a toast that says that the key is stored in the app or in the key store, and if the keystore is inside security hardware
* if not stored inside hardware, decrypted serialized key pair is kept. no need to store passphrase which is a plus i guess?
* not decrypting keys means they work faster (~500ms saved, sorry i was wrong about you sshj). not as fast as ssl but this is i suppose due to more messages that need to get back and forth until the connection is made
* BouncyCastle adds a mere 300KB since i suppose the rest can be stripped by ProGuard? or maybe OkHttp is using it? anyways that's not too much
* no significant increase in build time
* added a migration strategy for a seamless upgrading

cons:

* none! well actually some parts of code i'm not sure at and migration might break something but the testers (cough cough) will get care of this... won't they?

personal todo (wip):

- [ ] refactor preferences, some code could be moved elsewhere
- [ ] more fine-grained exceptions
- [ ] figure out what is worth translating...
- [ ] bug french ppl and german ppl to translate things
- [ ] [this code](https://github.com/ubergeek42/weechat-android/blob/099c92562bf0d867c47cfa5078d4a20ae535f8e5/app/src/main/java/com/ubergeek42/WeechatAndroid/utils/SecurityUtils.java#L55-L70) could probably be fixed to use BC api

**Comment by BlackDex** [comment]
@oakkitten Great! I just tested this on my Nokia 7.2, and works great :).
Generated a SSH-Key using JuiceSSH and used that, configured the host like this.

```bash
# WeeChat Relay - ED25519
no-agent-forwarding,no-X11-forwarding,permitopen="localhost:9000",command="echo 'Weechat Relay Only'" ssh-ed25519 AAAAC3....
```

**Comment by BlackDex** [comment]
Using at few days, still happy, no weird stuff.
Feels quick.
