### ISSUE TITLE
[Feature request] Auto-muting notifications for X minutes

### ISSUE THREAD

**Issue by KlavsKlavsen** [ubergeek42/weechat-android#445]
I would really love, if I could enable just a simple "min. notification interval" in minutes..
What happens today, is that someone writes to me, and weechat app pings me, and I then either go to my computer and respond, or I reply via app.
My problem is, that when I answer via pc (weechat in tmux), the app keeps notifying me for EVERY response, and since I am in a dialogue with someone - it says PING.. PING.. PING.. annoying all my colleagues and myself heavily :(
If I could just configure a min. notification interval - then I hope it would be simple to save timestamp for when last notification was sent, and then before actually sending notification - check if if its < than "min. notification interval".. I assume this should be implemented in here: https://github.com/ubergeek42/weechat-android/blob/fd6a07cb003caab703e6c63df55df5aa818b3133/app/src/main/java/com/ubergeek42/WeechatAndroid/service/Notificator.java#L156 ?

**Comment by KlavsKlavsen** [comment]
and a min notification interval of 10 minutes, would for me - be absolutely fine.. the conversation is often over within 10 minutes, and if not - I'm okay with a single ping again :)

**Comment by KlavsKlavsen** [comment]
Or perhaps its this function that I need to do it in: https://github.com/ubergeek42/weechat-android/blob/4f1a577bdef949de2b12e9216dc646d99b244ca9/app/src/main/java/com/ubergeek42/WeechatAndroid/relay/Hotlist.java#L198

**Comment by KlavsKlavsen** [comment]
Wrapping this line: https://github.com/ubergeek42/weechat-android/blob/4f1a577bdef949de2b12e9216dc646d99b244ca9/app/src/main/java/com/ubergeek42/WeechatAndroid/relay/Hotlist.java#L215 <- in a check for time since last notification > "min. notificatin interval" ? - would that be an acceptable solution? Then I'll try to see if I can compile the app and test locally, and learn enough java to fix it :)

**Comment by KlavsKlavsen** [comment]
Looking at modifying makenoise function https://github.com/ubergeek42/weechat-android/blob/fd6a07cb003caab703e6c63df55df5aa818b3133/app/src/main/java/com/ubergeek42/WeechatAndroid/service/Notificator.java#L291 (after tip from #weechat-android on freenode )

**Comment by oakkitten** [comment]
so there's two ways this can be handled, and maybe they both can be employed

- you can limit the sound alerts by implementing an option akin Smart Notifications in Telegram which simply limits notifications to x times in y minutes. this is useful if you are receiving a lot of notifications and is helpful regardless of how you use your computer

   this needs an additional option that sets x and y or disables the feature

- you can slightly delay the sound alert of a notification, only making noise if after x seconds the buffer is still unread in weechat. this is how Whatsapp and some other apps behave, and would be very helpful for when you are at your computer.

  this doesn't exactly need an additional option to set the delay but personally i would like to have it

perhaps the latter solution is enough

some notes:

1. in both cases we probably want to show the notification right away, and only limit or delay the sound & vibration. for older devices, this probably can be done by simply not calling `makeNoise`, for newer devices that rely on system-provided notification options we might need to use a different notification channel, e.g. “Hotlist (silent)”.
    1. should these silent notifications “Pop on screen” and show the light? if not, perhaps we can reuse the “Hotlist (async)” notification channel? it serves a slightly different purpose, though
2. in order to delay the sound of a notification, we'll probably have to
    * wait for a few seconds
    * sync hotlist
    * wait for the hotlist to sync
        * be prepared to handle disconnects during all the wait!
    * if the notification is still valid, make sound. make sure to not make sound if the notification was interacted with or dismissed!
3. places of interest & code notes:
    * `Hotlist` is supposed to maintain a valid local hotlist. it is local in the sense that it is not a mirror of WeeChat's hotlist.
    * you can use `BufferList.syncHotlist()` at any time to synchronize `Hotlist` with WeeChat's hotlist, that should clear any outstanding hot buffers, as well as notifications
    * look for `Hotlist.notifyHotlistChanged` called with `NotifyReason.HOT_SYNC`, that's where we are making noise
    * `Notificator` only issues notifications and doesn't deal with `Hotlist`'s logic. it doesn't call back to `Hotlist` when a notification is dismissed! so `Hotlist` can have a hot message in it, but `Notificator` might not know about it. it does maintain a list of open notifications (see `Notificator.notificaations`), but it's used for internal purposes only
    * to make sound for a notification already displayed, you probably want to simply reissue the same notification but this time use the regular notification channel and call `makeNoise`
    * would a thread to wait (e.g. AsyncTask) suffice? we may only want to sleep for a few seconds, but the system can put the cpu to sleep. use something else?
    * don't forget to check for synchronization issues if using a thread

a good place to start would be to look at how other apps do this

**Comment by oakkitten** [comment]
closing in favor of the linked issue
