### ISSUE TITLE
SSH Tunnel stopped working

### ISSUE THREAD

**Issue by j20d** [ubergeek42/weechat-android#465]
ssh-tunnel used to work, 1.1-dev just complains that the remote host is missing from the known-hosts.
I've tried to add a known-hosts-file by running ssh-keyscan into a file and using that file, that does unfortunately not change the behaviour.

If there's anything else I can provide please tell me.

**Comment by oakkitten** [comment]
if the error is `Hostname %s is not present in known hosts`, it should mean that the specified host name (`example.com`) or its IP addresses are not found in the hosts file. this happens if you e.g. run `$ ssh-keyscan loacalhost` instead of `$ ssh-keyscan example.com`.

if this is not the case, could you provide the output of your key scan (with identifiable information removed)?

**Comment by j20d** [comment]
Sure, the keyscan-file (`ssh-keyscan -p $port $host > keyscan.txt`) looks like this:
```
[hostname.domain.tld]:port-and-not-22 ssh-rsa 2k-RSA-key-goes-here
[hostname.domain.tld]:port-and-not-22 ecdsa-sha2-nistp256 ECDSA-key-goes-here
[hostname.domain.tld]:port-and-not-22 ssh-ed25519 ED25519-key-goes-here
```

**Comment by lucy** [comment]
Getting this too. Assuming it has something to do with using a non-22 port which I am as well.

**Comment by oakkitten** [comment]
so this could be interactive. if you are willing, please try [this build](http://weechat-android.ubergeek42.com/weechat-issue/465-42829ea.apk) (sorry about http) and see if it works for you
