### ISSUE TITLE
Add Support for Bubbles API?

### ISSUE THREAD

**Issue by tomatosoupcan** [ubergeek42/weechat-android#508]
I haven't had the time to take a deeper look at what all is required to support this, does anyone know off the top of their head how difficult this would be to implement?

**Comment by oakkitten** [comment]
this won't be as straightforward as it may seem

* as far as i can tell, on android <11 there isn't a cute li'l button inside notifications that opens the bubble. so one'd have to figure out how to offer the bubble to the user. (or simply don't do bubbles on android 10)

* our `BufferFragment` is somewhat tied to the activity that hosts it, and that activity is also managing the toolbar, and has the pager, etc. so you'd have to figure how to separate things. this is not exactly hard but we've got a lot of code inside the activity...

* more problematic would be synchronization of the input field. currently the data inside input fields is only preserved within the UI elements. this works fine for a single activity but if two activities can view the same buffer they probably should share the input.

  a major issue with this would be URI permissions. as per the docs,

  > Permissions granted in an Intent remain in effect while the stack of the receiving Activity is active. When the stack finishes, the permissions are automatically removed. Permissions granted to one Activity in a client app are automatically extended to other components of that app.

  if you have a bubble, i figure out that data shared to that buffer should go to the bubble. (hopefully we can figure out how to refer to that bubble.) but then the bubble will have the URI permission (ShareTextActivity (sic) transfers it via Intent and then destroys itself), and the main activity won't. i'm not quite sure how to deal with this situation. perhaps start another service that can keep the intent + permission for us? will that even work? somehow start main activity without actually displaying it?

* a `Buffer` currently can only have a single observer. not sure if there won't be any issues with having several

**Comment by oakkitten** [comment]
regarding the above points, i think we can
* only support bubbles on android 11+
* re: input synchronization; ignore media completely and do something very simple with text input
* don't show the toolbar in bubbles at all. not dealing with the menu, etc allows for a very simple decoupling.

otherwise, i think the behavior of the bubble is straightforward. except for one thing, whether we should keep the floating icon at all times or not. i think it's reasonable enough to preserve the icon once the bubble has been expanded at least once, and to dismiss it as a regular notification if not.

checklist for self:

* if never expanded, bubble icon is dismissed on buffer read
* if have been expanded, bubble icons stays until manually dismissed by user. this includes dragging to the ✖ area and pressing the ↖ button in the notification. check that
  * visiting the buffer doesn't dismiss it (in app or the bubble)
  * toggling wifi doesn't dismiss it
  * getting a notification in bubbling buffer and clearing it (via various means) doesn't dismiss it
  * getting a notification in another buffer and clearing it doesn't dismiss it
* the bubble alwas shows message ballon on new message. needs DND off! especially check that it works right after visiting the bubble
* check that read marker behaves in a sane way
* check that activity recreation works (e.g. when switching theme)
   * check that this doesn't screw up buffer open status?
* see if it's possible to recreate notification without showing ballons? maybe drop recreation at all?

it would be nice to be able to detect bubble dismissal better

**Comment by oakkitten** [comment]
turns out we can detect bubble dismissal better after all.

so far this is all good but there are two problems here that might be unsolvable but not a blocker:

* whenever a notification is updated, its bubble, if any, will show a balloon with the last message. we are updating the notification to remove the “reply” action whenever offline, or add it back when online. so we don't want any balloons here. a balloon:
  <img src="https://user-images.githubusercontent.com/1710718/119355024-a723e680-bc9c-11eb-8b40-6820a7fd2a05.png" width=150>

  i don't think there's a way to prevent this from happening, mainly because the system *does* realize this is not a new message but shows the balloon anyway. you can tell this by the fact that there's no animation for such updates. (interestingly, for `/me` actions, there is animation. this is because such actions are italicized, and we're using `SpannedString` for that, and it has a bug; its `equals()` method is broken, so it's thinking every italicized line is a different one.)

  solutions:

  * don't add/remove the action. this is a bit problematic as then we have to deal with an action that can't be executed. the notificaton will present a loading spinner that spins until the message is “sent”, so we'd have to have the machinery to cancel that and to alert the user that their message wasn't sent. this is bad ux and more work
  
  * ignore the issue

* it seems that it's impossible to remove a notification but leave a bubble when the app is in background. we are removing notification when the buffer is read it the app (main activity or bubble), as well as when the buffer has been read in weechat. in order to remove the notification, but keep the bubble, we actually have to repost the notification but [set a flag that suppresses it on bubble metadata](https://developer.android.com/reference/android/app/Notification.BubbleMetadata.Builder#setSuppressNotification(boolean)). this works great, but for some reason this flag has no effect when posted when app is not visible to the user.

  currently this results in the posted empty notification being visible to the user:
  <img src="https://user-images.githubusercontent.com/1710718/119355273-fa963480-bc9c-11eb-9309-6a826db0d7bd.png" width=300>

  solutions:

  * keep the notification as is. this is awkward as the app will be showing that the message has been read... also this could be a bit annoying to implement as we are not keeping notification data, and hotlist data would be lacking old lines

  * remove the notification. bad ux, i think the bubble should be kept until dismissed by user

  * ignore the issue

**Comment by oakkitten** [comment]
there's yet another issue. what is now on branch api-30 tracks notifications using buffer full names; this is a bit of a problem as these can change in the normal use of weechat

it works like this; you post a notification with a notification key, and you attach a conversation key to it. the latter must be long-lived, it's something that you can pin in the launcher. it makes sense to use stuff like `irc.libera.foo` here. you would want to use the same key for the notification itself for simplicity.

however when user changes their nick, weechat will also change the full name of the buffer. perhaps it makes sense, but we now have a problem as this disassociates the buffer from its notifications. old notifications won't get removed or updated and tapping on them would not work.

what we can do is

* try to keep the old conversation key. this can be insanely complicated

* use different keys for notifications themselves, derived from buffer pointer. this is the way it works on current master. but, this means that occasionally we will be updating the notification with a conversation key different from one used before. this is a rather weird thing to do and some systems might not behave well around this

  on lineageos 18, this seems to kind of work. if conversation `foo` is not bubbling and `bar` is, updating `foo` to `bar` will show the bubble (with a balloon, which is a different issue mentioned above) and will hide it the other way around. also the icon will change to a differently colored one; this we want actually

  one issue (bug?) with this is, if there's a bubble without a notification, posting another notification with a changed conversation key will result in the notification getting dismissed. this is very weird. to reproduce:

  * join a channel with `foo` in it
  * get pm notification from `foo`, bubble it, minimize bubble
  * `foo` changes nick to `bar`
  * `bar` pms you. the bubble disappears, and the notification does not appear either

**Comment by oakkitten** [comment]
bubbles have been implemented

**Comment by oakkitten** [comment]
there's another issue here that can't be fixed in a sane way. we need to reliably determine if a notification can bubble and this might not be entirely possible. we need this information:

* to not update a notification if it can bubble. if it can bubble, its dismiss listener is not called, and an update can bring back a dismissed notification.
* to cancel notifications properly. to cancel a bubbling notification, we need to republish a suppressed notification instead. 

there are two tiers of settings:

* per-app setting:
  * all conversations can bubble
  * selected conversations can bubble (default)
  * nothing can bubble

* per-conversation settings
  * bubble this conversation
  * don't bubble this conversation
  * default

these interact in the following way:
* if all convesations can bubble, bubble this conversation unless it is set to not bubble
* if selected conversations can bubble, only bubble if this conversation is set to bubble
* if nothing can bubble, ignore per-conversation settings

|        |yes|no|default|
|--------|:-:|:-:|:----:|
|all     |💬 |   |  💬 |
|selected|💬 |   |      |
|nothing |   |   |      |

the problem: method `manager.areBubblesAllowed()` returns true for “all conversations can bubble” and false otherwise, and `channel.canBubble()` returns true if “bubble this conversation” is on and false otherwise. so there are certain cases that we can't reliably detect (✖️) and some of them are problematic (❌) as we can't really know if the bubble will be shown or not:

|        |yes|no|default|
|--------|:-:|:-:|:----:|
|all     |   | ❌ |  ❌ |
|selected| ❌| ✖️ | ✖️ |
|nothing | ❌| ✖️ | ✖️ |

getting channel settings can be mitigated through reflection/`channel.toString()` as it exposes field `mAllowBubbles` that can be -1 for default, and 1 or 0 for bubble/don't bubble. but i'm not sure anything can be done about `manager.areBubblesAllowed()`

**Comment by oakkitten** [comment]
it's usual to open bubbles from notifications. i'm not sure that i know of one app, apart from the cats & dogs notifications demo app, that offers other ways of opening bubbles

**Comment by bqv** [comment]
Any chance you'd consider trying it? :)
