### ISSUE TITLE
fails to connect when using a wildcard letsencrypt certificate

### ISSUE THREAD

**Issue by jcolson** [ubergeek42/weechat-android#540]
i've symlinked the letsencrypt wildcard certificate from it's source directory to my .weechat/ssl/relay.pem location for weechat.

the certificate is found and served by weechat with no issues.

weechat-android misinterprets the full chain, however.  ISRG is a root certificate, however, for some reason weechat-android thinks that it was issued by DST Root, and determines that it is an expired certificate.

Screen shots:
ISRG root cert
![isrg_root_cert](https://user-images.githubusercontent.com/2362647/173191147-f6c77e09-7042-4932-9ba1-1712ba5c045e.jpg)

DST root cert (that weechat-android displays)
![dst_root_cert](https://user-images.githubusercontent.com/2362647/173191157-2e04a562-1008-4ad6-b3c7-3ae7c40d2746.jpg)

**Comment by oakkitten** [comment]
This sounds super weird. It would help to see the actual chain, could you drop by our IRC channel (#weechat-android at libera)?

**Comment by DjSlash** [comment]
Had the same issue. When using Let's Encrypts `fullchain.pem` in the relay certificate, weechat-android would complain that the DST Root certificate is expired. Changed it to contain `cert.pem`, with `privkey.pem` of course, and it works.

**Comment by oakkitten** [comment]
Version 1.8 has been just released, it should solve this issue among others. In case of a TLS error, we were making another request to get the certificate chain, since you can make a gangster's chain of the loops and hoops you have to jump through to get one from a connection that fails (thanks Java). That another request was verifying the chain in a dumb way, which worked for most cases but failed in this one with multiple possible trust chains and an expired certificate to boot. 

Also, the certificate dialog used to show the server supplied chain with a root certificate attached to the certificate farthest from the leaf. This is not the best idea, as server can supply random certificates in any order. Now we are displaying the system trusted chain, if available, and server supplied certificates as is, if not.

Please tell us if there any more issues with this!

(None of this was a security issue, only a problem with the way the error message was displayed.)
