### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [ubergeek42/weechat-android#542]
`storage.googleapis.com/r8-releases/raw` is not allowed in fdroidserver. We need to wait until `com.android.tools:r8:3.3.62` available in MavenCentral.

**Comment by oakkitten** [comment]
> storage.googleapis.com/r8-releases/raw is not allowed in fdroidserver

Huh, why not? We were using that before as well.

**Comment by linsui** [comment]
F-Droid only allows some well-known repos (maven central, google, etc.). We can build it from source of course but not sure how difficult it is. It was a stupid bug that the fdroidserver scanner doesn't scan build.gradle.kts files.

**Comment by oakkitten** [comment]
Is that a recent change? I mean we were using that [in 1.7](https://github.com/ubergeek42/weechat-android/blob/v1.7/build.gradle.kts#L25) as well. And why disallow repos in the first place? And why the R8 repo is not “well-known“? ._.

**Comment by mhoran** [comment]
Well I think this means it was able to pull the older version of r8 from Maven Central; but now that we need a new version that is only in the r8 repo, fdroid builds fail.

**Comment by linsui** [comment]
It's a [recent fix](https://gitlab.com/fdroid/fdroidserver/-/merge_requests/1119). We need to ensure that all deps are foss and it would be an impossible task for us to check every random repos. So we only allow some well-known repos.

**Comment by oakkitten** [comment]
I don't like this.

First of all, you are saying that you do not trust the developers with making sure that their dependencies are open source, which is a tad insulting. Or, that you don't trust us at all, which is a tad ridiculous since you are not vetting the code.

I asked if R8 repository, which only has R8, can be allowlisted and that apparently is too much. So you don't trust Google either.

Then—correct me if I am wrong here—there are legitimate uses for non-FOSS in FOSS projects. If I use Photoshop to edit a picture, that doesn't make the picture itself non-free, does it? Similarly, even if R8 was non-free, isn't the bytecode that it produced still free and open source, as much as bytecode can be open source?

Lastly, you are trusting Maven Central, I guess. Correct me if I am wrong, again, but I don't think Central actually requires the projects to have a FOSS license. You have to provide the license, and the source code. But it doesn't have to be FOSS.

I'm not sure how any of this helps. 🤔

Anyway, the fix in R8 that we need is apparently incorporated into the beta AGP. So we can drop the extra repository. So I guess we'll release 1.8.1 in a few days and this can be closed.

**Comment by linsui** [comment]
> First of all, you are saying that you do not trust the developers with making sure that their dependencies are open source, which is a tad insulting. Or, that you don't trust us at all, which is a tad ridiculous since you are not vetting the code.

I apologize if you feel so: we are not saying that the developers are evil or untrusted. But we need some mechanism to help ensure the source code align our standard. Not all developers have the same target with us. We want to make sure that the deps are FOSS but they make want to provide better UI.

As a user, I can trust you. But we can't just keep adding more rules, it's not maintainable. I thought the "trusted maven repos' are more about the pratice: they are not the most trustable repos and others are just evil, but these repos are the most well known ones so they cover most use cases.

> Lastly, you are trusting Maven Central, I guess. Correct me if I am wrong, again, but I don't think Central actually requires the projects to have a FOSS license. You have to provide the license, and the source code. But it doesn't have to be FOSS.

No, you don't need to provide the source code, see https://central.sonatype.org/faq/closed-source/. Unfornately, it's not realitic to block Maven Central. So we add those libs into our blocklist. Adding more trusted repos will bring more problems.

**Comment by mhoran** [comment]
1.8.1 released on F-Droid using the latest Android Gradle Plugin. Thanks all for the help!
