### ISSUE TITLE
certificate pinning

### ISSUE THREAD

**Issue by ghost** [ubergeek42/weechat-android#94]
I'd like to request certificate pinning for WeechatSSL.
This could be as simple as checking the thumbprint or it could be CA pinning.

**Comment by oakkitten** [comment]
i definitely want to see something like this in the app, but i'm not quite sure how to go about this.

we are already asking the user about self-signed certificates, so pinning would be more useful regarding regular validated certificates such as those issued by letsencrypt. there's an immediate problem with these: these certificates are rather short-lived. so pins are going to fail often, and we'd have to deal with this in a way that's not too frustrating to the user.

it would be also nice to give the user a choice as to which cert of the cert chain to pin

i see several options:

1. have a new setting, "Certificate pin" or something, that would accept a SHA-256 or a SHA-1 fingerprint, that would be matched against the certificate chain. if it is not empty and doesn't match any of the certificates, we fail the connection with a toast. this would be the simplest to implement but would require a lot of work on the part of the user

    also we could support several pins here

2. same as the above but instead of the setting we have a checkbox and the pin is filled by asking the user about what cert they want to pin. this would require a lot of work on the part of the developers, as we'd have to present the list of certificates

3. same of the above but we only show the leaf certificate. this would be basically the same as treating all certificates as untrusted ones. might be not too hard to implement?

4. we could also rely on some mechanism such as HPKP, something that would rotate the pins for us. HPKP is deprecated, however, and this would be the hardest to implement
