### ISSUE TITLE
weechat-android cannot access ssh private keys under Kitkat

### ISSUE THREAD

**Issue by Soft** [ubergeek42/weechat-android#96]
After updating to Kitkat, weechat-android can no longer access my ssh private keys. When trying to connect the client displays following error:

```
Error: java.io.FileNotFoundException: /storage/emulated/0/secret.key: open failed: EACCES (Permission denied)
```

I am pretty sure the path I have entered is correct, since it worked under previous version of android and I don't think this is a device dependent issue since I have faced the same issue with two of my devices.

**Comment by abjugard** [comment]
I am having this exact issue after upgrading to Marshmallow (Nexus 5X).

**Comment by okuuva** [comment]
Same here, passphrase protected SSH key stopped working after upgrading to Marshmallow on Oneplus One.

**Comment by ubergeek42** [comment]
I guess we'll have to take a look at this again.

**Comment by stysmmaker** [comment]
On Marshmallow I was having the same issue; figured out it was caused by weechat not having permission to access storage, so I just went into app settings and gave the app sufficent permission. Works fine now. Using LG G4.

**Comment by gilandose** [comment]
Yes I had to do the same as @stysmmaker to get it to work, think it's due to how marshmallow handles permissions, rather than grant the app permission at install, Marshmallow apps must request permission when they first do the activity that requires a new permission be granted. IE an app that allows sending picture messages doesn't get granted permission to access camera until you try to send and take first picture.. App should perform a system call to ask if it can have the storage permission if it does not currently have it.

**Comment by PMaynard** [comment]
CM 13 - Android 6. Fresh Install.
Current Weechat-Android 0.11

I was not prompted to give permission. 

Settings -> Apps -> Cog at the top -> App permission -> Scroll down to storage -> Enable for weechat-android.

**Comment by BetaRays** [comment]
I think the problems that happen in marshmallow is due to the fact that weechat-android doesn't ask for the storage permission.
« Beginning in Android 6.0 (API level 23), users grant permissions to apps while the app is running, not when they install the app. » https://developer.android.com/training/permissions/requesting.html
This is also described in #356 for fonts, but it's also necessary for SSH keys outside of the app's own data.

**Comment by fsch2** [comment]
I can confirm that giving the app the storage permissions manually as outlined by PMaynard works for me. Using Weechat-Android 0.11 and Android version 6.0.1.
